### ISSUE TITLE
No longer working reached max rules per Security Group

### ISSUE THREAD

**Issue by kleinerator** [aws-samples/aws-cloudfront-samples#11]
This solution no longer works. I've reached the max rules per security group and now I'm getting weird issues.

**Comment by knowhy** [comment]
The 50 rules per security group limit can be increased via [AWS support](https://aws.amazon.com/premiumsupport/knowledge-center/increase-security-group-rule-limit/).

**Comment by ajitchahal** [comment]
We have increased the limit to > 50 rules per security group, but the lambda code only creates 33 rules even though there are 59 rules to be created.

**Comment by rarylson** [comment]
I did a test today, and get the following results:

```console
$ curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes | map(select(.service == "CLOUDFRONT") | select(.region == "GLOBAL")) | length'
36

$ curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes | map(select(.service == "CLOUDFRONT") | select(.region != "GLOBAL")) | length'
31
```

It is, it's expected to have 36 rules in the SG `cloudfront_g`, and 31 rules in the SG `cloudfront_r`.

So, I've tested the lambda function, and everything worked well.

I think this is fixed since commit 340f9d.

I guess the "aws-cloudfront-samples" owners could close this issue now.

**Comment by baldwinmatt** [comment]
Resolved
